import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { UserProvider } from '@auth0/nextjs-auth0/client'; //https://manage.auth0.com/dashboard/us/dev-dkzkimwgxvq1q7r1/applications/7JJlG358N7UzbwnpwOTPJ9MUzM50ut9V/quickstart/nextjs
import Nav from '@/compoents/Nav';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Investify',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
      <UserProvider>
      <body className={cn(
        'min-h-screen font-sans antialiased grainy',
        inter.className
      )}>
        <Nav />
        <link className=" rounded-3xl '" rel="icon" href="/pixelcut-export.jpg" />
        {children}
        </body>
      
      </UserProvider>
    </html>
  )
}
